Coffee shop detail icon
hegelocampus/Roastia pull request #106
Opened 2019-12-12 01:37 UTC by uwgnol1612

2019-12-12 22:42 UTC, hegelocampus requested changes
Those accessibility issues that were marked by accesslint bot need to be addressed, **employers heavily value attention to accessibility issues**

2019-12-13 01:00 UTC, uwgnol1612 commented on client/src/components/main/coffee_shop/CoffeeShop.js
> +              <img src="https://we-camp-seeds.s3.us-east-2.amazonaws.com/Coffee+bar+year.png" />
Fixed

2019-12-13 01:00 UTC, uwgnol1612 commented on client/src/components/main/coffee_shop/CoffeeShop.js
> +              <img src="https://we-camp-seeds.s3.us-east-2.amazonaws.com/Coffee+bar+type.png" />
Fixed

2019-12-13 01:00 UTC, uwgnol1612 commented on client/src/components/main/coffee_shop/CoffeeShop.js
> +              <img src="https://we-camp-seeds.s3.us-east-2.amazonaws.com/Coffee+website.png" />
Fixed

2019-12-13 01:01 UTC, uwgnol1612 commented on client/src/components/main/coffee_shop/CoffeeShop.js
> +              <img src="https://we-camp-seeds.s3.us-east-2.amazonaws.com/Coffee+satisfaction.png" />
Fixed

2019-12-13 01:03 UTC, hegelocampus approved these changes
Great! Thank you!

2019-12-13 01:03 UTC, merged